import { RidePoint } from '@/lib/store/useRideStore';
import { auth, firestore } from '@/lib/utils/firebaseConfig';
import { collection, doc, setDoc, writeBatch } from '@react-native-firebase/firestore';
import storage, { deleteObject } from '@react-native-firebase/storage';

export interface AutoGeneratedAnnotation {
    id: string;
    inferredAnnotation: string;
    startTime: string;
    endTime: string;
    accepted: boolean;
}

export interface Annotation {
    id: string;
    rideId: string;
    userId: string;
    mediaUri?: string;
    mediaType?: string;
    points: RidePoint[];
    sentiment?: string;
    annotationId: string;
    type: 'point' | 'segment';
    additionalTags?: string[];
    autoGeneratedAnnotations?: AutoGeneratedAnnotation[];
    autoAnnotationSeen?: boolean;
    createdAt: number;
    source?: 'auto-generated-from-video';
    timestamp?: number;
    start_timestamp?: number;
    end_timestamp?: number;
}

export interface NewAnnotation extends Omit<Annotation, 'createdAt'> {
    createdAt: Date;
}

export const saveAnnotation = async (
    annotation: Omit<Annotation, 'id' | 'userId' | 'createdAt'>
): Promise<Annotation> => {
    try {
        const userId = auth.currentUser?.uid;
        if (!userId) {
            throw new Error('User not authenticated');
        }

        const ridesCollectionRef = collection(firestore, 'rides');
        const rideDocRef = doc(ridesCollectionRef, annotation.rideId);

        const annotationsCollectionRef = collection(rideDocRef, 'annotations');
        const annotationDocRef = doc(annotationsCollectionRef);
        const uploadMedia = async (mediaUri: string) => {
            const mediaRef = storage().ref(`rides/${rideDocRef.id}/annotations/${annotationDocRef.id}`);

            const task = mediaRef.putFile(mediaUri);

            task.on('state_changed', snapshot => {
                console.log('Upload is ' + snapshot.bytesTransferred);
            });

            await task;
            return await mediaRef.getDownloadURL();
        };

        const annotationData = {
            ...annotation,
            mediaUri: annotation.mediaUri ? await uploadMedia(annotation.mediaUri) : null,
            mediaType: annotation.mediaType || null,
            sentiment: annotation.sentiment || null,
            additionalTags: annotation.additionalTags || null,
            autoGeneratedAnnotations: annotation.autoGeneratedAnnotations || null,
            autoAnnotationSeen: annotation.autoAnnotationSeen || null,
            source: annotation.source || null,
            timestamp: annotation.timestamp || null,
            start_timestamp: annotation.start_timestamp || null,
            end_timestamp: annotation.end_timestamp || null,
            id: annotationDocRef.id,
            userId: userId,
            rideId: rideDocRef.id,
            createdAt: new Date().getTime(),
        } as Annotation;

        await setDoc(annotationDocRef, annotationData);

        return annotationData;
    } catch (error) {
        console.error('Error fetching annotations:', error);
        throw error;
    }
};

export const deleteAnnotation = async (annotation: Annotation) => {
    try {
        const userId = auth.currentUser?.uid;
        if (!userId) {
            throw new Error('User not authenticated');
        }

        const batch = writeBatch(firestore);

        // Add annotation deletion to batch
        const annotationsCollectionRef = collection(firestore, 'rides', annotation.rideId, 'annotations');
        const annotationDocRef = doc(annotationsCollectionRef, annotation.id);
        batch.delete(annotationDocRef);

        if (annotation.mediaUri) {
            const mediaRef = storage().ref(`rides/${annotation.rideId}/annotations/${annotation.id}`);
            await deleteObject(mediaRef);
        }

        // Commit the batch
        await batch.commit();
    } catch (error) {
        console.error('Error removing annotation:', error);
        throw error;
    }
};
