import { GeneratedRoute, RidePoint } from '@/lib/store/useRideStore';
import { firestore } from '@/lib/utils/firebaseConfig';
import { getAuth } from '@react-native-firebase/auth';
import {
    average,
    collection,
    count,
    doc,
    getAggregateFromServer,
    getCountFromServer,
    getDoc,
    getDocs,
    getFirestore,
    limit,
    orderBy,
    query,
    startAfter,
    sum,
    updateDoc,
    where,
    writeBatch,
} from '@react-native-firebase/firestore';
import storage, { deleteObject } from '@react-native-firebase/storage';
import { startOfMonth, startOfWeek } from '../common/dateOptions';
import { Annotation, AutoGeneratedAnnotation } from './annotations';

export interface RideData {
    rideName: string;
    startTime: number;
    endTime: number;
    duration: number;
    distance: number;
    suggestedRouteDistanceM?: number;
    suggestedRouteDurationSec?: number;
    averageSpeed: number;
    maxSpeed: number;
    elevationGain: number;
    annotations: Annotation[];
    points: RidePoint[];
    isPublic: boolean;
    isGPXUpload?: boolean;
    fromWeb?: boolean;
    rideVideo?: string;
    autoGeneratedAnnotations?: AutoGeneratedAnnotation[];
    autoAnnotationSeen?: boolean;
}

export interface NewRideData extends Omit<RideData, 'id' | 'createdAt' | 'annotations'> {
    annotations: Omit<Annotation, 'id' | 'timestamp' | 'userId' | 'createdAt' | 'rideId'>[];
    generatedRoutes?: GeneratedRoute[];
}

export interface FetchRideData extends RideData {
    id: string;
    createdAt: number;
    userId: string;
}

export interface OfflineRideData extends RideData {
    offlineId: string;
    createdAt: number;
}

interface PaginationOptions {
    limit: number;
    startAfter?: string | null;
}

interface PaginatedResponse<T> {
    items: T[];
    lastDocId: string | null;
    hasMore: boolean;
}

export const getRides = async (
    userId: string,
    options: PaginationOptions,
    community: boolean = false
): Promise<PaginatedResponse<FetchRideData>> => {
    try {
        const ridesCollectionRef = collection(getFirestore(), 'rides');
        let q;

        if (community) {
            q = query(
                ridesCollectionRef,
                where('isPublic', '==', true),
                orderBy('createdAt', 'desc'),
                limit(options.limit)
            );
        } else {
            q = query(
                ridesCollectionRef,
                where('userId', '==', userId),
                orderBy('createdAt', 'desc'),
                limit(options.limit)
            );
        }

        if (options.startAfter) {
            const lastDoc = await getDoc(doc(ridesCollectionRef, options.startAfter));
            if (lastDoc.exists()) {
                q = query(q, startAfter(lastDoc));
            }
        }

        const snapshot = await getDocs(q);
        const rides: FetchRideData[] = [];

        for (const doc of snapshot.docs) {
            const data = doc.data();
            rides.push({
                id: doc.id,
                ...data,
            } as FetchRideData);
        }

        return {
            items: rides,
            lastDocId: snapshot.docs[snapshot.docs.length - 1]?.id || null,
            hasMore: snapshot.docs.length === options.limit,
        };
    } catch (error) {
        console.error('Error fetching rides:', error);
        throw error;
    }
};

export const getRidePoints = async (userId: string, rideId: string): Promise<RidePoint[]> => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const mapCollectionRef = collection(rideDocRef, 'map');
        const pointsDocRef = doc(mapCollectionRef, 'points');

        const pointsDoc = await getDoc(pointsDocRef);
        if (!pointsDoc.exists()) {
            return [];
        }

        const data = pointsDoc.data() as { items?: RidePoint[] };
        return data.items ?? [];
    } catch (error) {
        console.error('Error fetching ride points:', error);
        throw error;
    }
};

export const getRideAnnotations = async (userId: string, rideId: string): Promise<Annotation[]> => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');

        const annotationsDoc = await getDocs(annotationsCollectionRef);

        const annotations: Annotation[] = [];
        for (const doc of annotationsDoc.docs) {
            const data = { ...doc.data(), id: doc.id };
            annotations.push(data as Annotation);
        }

        return annotations;
    } catch (error) {
        console.error('Error fetching ride annotations:', error);
        throw error;
    }
};

export const saveRide = async (rideData: NewRideData) => {
    try {
        const userId = getAuth().currentUser?.uid;
        if (!userId) {
            throw new Error('User not authenticated');
        }
        const ridesCollectionRef = collection(firestore, 'rides');

        const batch = writeBatch(firestore);
        // Save main ride data without points
        const { points, annotations = [], generatedRoutes = [], isGPXUpload, fromWeb, ...rideDataWithoutPoints } = rideData;

        if (!points || points.length === 0) {
            throw new Error('No ride points provided');
        }

        let gpxUpload = false;
        let webSource = false;
        if (isGPXUpload) {
            gpxUpload = true;
        }
        if (fromWeb) {
            webSource = true;
        }

        const rideDocRef = doc(ridesCollectionRef);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');
        const processedAnnotations = await Promise.all(
            annotations.map(async annotation => {
                if (!annotation) {
                    return;
                }

                const annotationDocRef = doc(annotationsCollectionRef);
                const uploadMedia = async (mediaUri: string) => {
                    if (!mediaUri) {
                        return null;
                    }
                    const mediaRef = storage().ref(`rides/${rideDocRef.id}/annotations/${annotationDocRef.id}`);
                    const task = mediaRef.putFile(mediaUri);

                    task.on('state_changed', snapshot => {
                        console.log('Upload is ' + snapshot.bytesTransferred);
                    });
                    await task;
                    return await mediaRef.getDownloadURL();
                };
                batch.set(annotationDocRef, {
                    ...annotation,
                    mediaType: annotation.mediaType ?? null,
                    mediaUri: annotation.mediaUri ? await uploadMedia(annotation.mediaUri) : null,
                    id: annotationDocRef.id,
                    userId: userId,
                    rideId: rideDocRef.id,
                    createdAt: Date.now(),
                });
            })
        );

        batch.set(rideDocRef, {
            ...rideDataWithoutPoints,
            id: rideDocRef.id,
            userId: userId,
            createdAt: Date.now(),
            isGPXUpload: gpxUpload,
            fromWeb: webSource,
        });

        // Save generated routes to top-level generatedRoutes collection
        const generatedRoutesCollectionRef = collection(firestore, 'generatedRoutes');
        generatedRoutes.forEach(route => {
            const routeDocRef = doc(generatedRoutesCollectionRef, route.routeId);
            batch.set(routeDocRef, {
                ...route,
                rideId: rideDocRef.id,
            });
        });

        // Save points in a single document under map/points
        const mapCollectionRef = collection(rideDocRef, 'map');
        const pointsDocRef = doc(mapCollectionRef, 'points');
        batch.set(pointsDocRef, {
            items: points,
        });

        await batch.commit();

        return rideDocRef.id;
    } catch (error) {
        console.error('Error saving ride:', error);
        throw error;
    }
};

export const getRide = async (userId: string, rideId: string): Promise<FetchRideData> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const rideDocRef = doc(ridesCollectionRef, rideId);
        const rideDoc = await getDoc(rideDocRef);

        if (!rideDoc.exists()) {
            throw new Error('Trip not found');
        }
        const rideData = rideDoc.data() as FetchRideData;

        return {
            ...rideData,
            id: rideDocRef.id,
        };
    } catch (error) {
        console.error('Error getting ride:', error);
        throw error;
    }
};

export const updateRideName = async (userId: string, rideId: string, newName: string) => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        await updateDoc(rideDocRef, { rideName: newName });
    } catch (error) {
        console.error('Error updating ride name:', error);
        throw error;
    }
};

export const getTotalRideCount = async (userId: string): Promise<number> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const q = query(ridesCollectionRef, where('userId', '==', userId));
        const count = await getCountFromServer(q);
        return count.data().count;
    } catch (error) {
        console.error('Error fetching total rides:', error);
        throw error;
    }
};

export const getWeeklyRideCount = async (userId: string) => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const q = query(
            ridesCollectionRef,
            where('userId', '==', userId),
            where('createdAt', '>=', startOfWeek(new Date()).getTime()),
            where('createdAt', '<=', new Date().getTime())
        );
        const count = await getCountFromServer(q);
        return count.data().count;
    } catch (error) {
        console.error('Error fetching weekly rides:', error);
        throw error;
    }
};

export const getMonthlyDistanceAndCount = async (userId: string): Promise<{ distance: number; count: number }> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const q = query(
            ridesCollectionRef,
            where('userId', '==', userId),
            where('createdAt', '>=', startOfMonth(new Date()).getTime()),
            where('createdAt', '<=', new Date().getTime())
        );
        const snapshot = await getAggregateFromServer(q, {
            distance: sum('distance'),
            count: count(),
        });
        if (!snapshot.data()) {
            return { distance: 0, count: 0 };
        }
        const data: { distance: number; count: number } = snapshot.data() as { distance: number; count: number };
        return { distance: data?.distance || 0, count: data?.count || 0 };
    } catch (error) {
        console.error('Error fetching monthly distance:', error);
        throw error;
    }
};

export const getTotalDistanceAndCountAndAverageSpeedAndElevation = async (
    userId: string
): Promise<{ distance: number; count: number; averageSpeed: number; elevation: number }> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const q = query(ridesCollectionRef, where('userId', '==', userId), orderBy('createdAt', 'desc'));
        const snapshot = await getAggregateFromServer(q, {
            distance: sum('distance'),
            count: count(),
            averageSpeed: average('averageSpeed'),
            elevationGain: sum('elevationGain'),
        });

        if (!snapshot.data()) {
            return { distance: 0, count: 0, averageSpeed: 0, elevation: 0 };
        }

        const data: { distance: number; count: number; averageSpeed: number; elevationGain: number } =
            snapshot.data() as {
                distance: number;
                count: number;
                averageSpeed: number;
                elevationGain: number;
            };

        return {
            distance: data?.distance || 0,
            count: data?.count || 0,
            averageSpeed: data?.averageSpeed || 0,
            elevation: data?.elevationGain || 0,
        };
    } catch (error) {
        console.error('Error fetching total distance:', error);
        throw error;
    }
};

export const getLongestRide = async (userId: string): Promise<number> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const q = query(ridesCollectionRef, where('userId', '==', userId), orderBy('distance', 'desc'), limit(1));
        const snapshot = await getDocs(q);
        if (snapshot.docs.length === 0) {
            return 0;
        }
        return snapshot.docs[0].data().distance;
    } catch (error) {
        console.error('Error fetching longest ride:', error);
        throw error;
    }
};

export const deleteRide = async (ride: FetchRideData) => {
    try {
        const rideDocRef = doc(firestore, 'rides', ride.id);
        const batch = writeBatch(firestore);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');
        const annotationsDocRefs = ride.annotations.map(annotation => {
            const mediaRef = storage().ref(`rides/${ride.id}/annotations/${annotation.id}`);
            return {
                docRef: doc(annotationsCollectionRef, annotation.id),
                mediaRef: mediaRef,
            };
        });
        annotationsDocRefs.forEach(docRef => {
            batch.delete(docRef.docRef);
            deleteObject(docRef.mediaRef);
        });
        const pointsDocRef = doc(collection(rideDocRef, 'map'), 'points');
        batch.delete(rideDocRef);
        batch.delete(pointsDocRef);
        await batch.commit();
    } catch (error) {
        console.error('Error deleting ride:', error);
        throw error;
    }
};

export const updateVisibilitySettings = async (rideId: string, visibility: boolean) => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const res = await updateDoc(rideDocRef, {
            isPublic: visibility,
        });

        console.log(res);
    } catch (error) {
        console.error('Error saving visibility settings.');
        throw error;
    }
};
