import { GeneratedRoute, RidePoint } from '@/lib/store/useRideStore';
import { firestore } from '@/lib/utils/firebaseConfig';
import { getAuth } from '@react-native-firebase/auth';
import {
    average,
    collection,
    count,
    doc,
    getAggregateFromServer,
    getCountFromServer,
    getDoc,
    getDocs,
    getFirestore,
    limit,
    orderBy,
    query,
    startAfter,
    sum,
    updateDoc,
    where,
    writeBatch,
} from '@react-native-firebase/firestore';
import storage, { deleteObject } from '@react-native-firebase/storage';
import { startOfMonth, startOfWeek } from '../common/dateOptions';
import { Annotation, AutoGeneratedAnnotation } from './annotations';

export interface RideData {
    rideName: string;
    startTime: number;
    endTime: number;
    duration: number;
    distance: number;
    suggestedRouteDistanceM?: number;
    suggestedRouteDurationSec?: number;
    averageSpeed: number;
    maxSpeed: number;
    elevationGain: number;
    annotations: Annotation[];
    points: RidePoint[];
    isPublic: boolean;
    isGPXUpload?: boolean;
    fromWeb?: boolean;
    rideVideo?: string;
    autoGeneratedAnnotations?: AutoGeneratedAnnotation[];
    autoAnnotationSeen?: boolean;
}

export interface NewRideData extends Omit<RideData, 'id' | 'createdAt' | 'annotations'> {
    annotations: Omit<Annotation, 'id' | 'timestamp' | 'userId' | 'createdAt' | 'rideId'>[];
    generatedRoutes?: GeneratedRoute[];
}

export interface FetchRideData extends RideData {
    id: string;
    createdAt: number;
    userId: string;
}

export interface OfflineRideData extends RideData {
    offlineId: string;
    createdAt: number;
}

interface PaginationOptions {
    limit: number;
    startAfter?: string | null;
}

interface PaginatedResponse<T> {
    items: T[];
    lastDocId: string | null;
    hasMore: boolean;
}

export const getRides = async (
    userId: string,
    options: PaginationOptions,
    community: boolean = false
): Promise<PaginatedResponse<FetchRideData>> => {
    try {
        return await retryWithBackoff(async () => {
            const ridesCollectionRef = collection(getFirestore(), 'rides');
            let q;

            if (community) {
                q = query(
                    ridesCollectionRef,
                    where('isPublic', '==', true),
                    orderBy('createdAt', 'desc'),
                    limit(options.limit)
                );
            } else {
                q = query(
                    ridesCollectionRef,
                    where('userId', '==', userId),
                    orderBy('createdAt', 'desc'),
                    limit(options.limit)
                );
            }

            if (options.startAfter) {
                const lastDoc = await getDoc(doc(ridesCollectionRef, options.startAfter));
                if (lastDoc.exists()) {
                    q = query(q, startAfter(lastDoc));
                }
            }

            const snapshot = await getDocs(q);
            const rides: FetchRideData[] = [];

            for (const doc of snapshot.docs) {
                const data = doc.data();
                rides.push({
                    id: doc.id,
                    ...data,
                } as FetchRideData);
            }

            return {
                items: rides,
                lastDocId: snapshot.docs[snapshot.docs.length - 1]?.id || null,
                hasMore: snapshot.docs.length === options.limit,
            };
        });
    } catch (error) {
        if (isTransientFirestoreError(error)) {
            console.warn('Fetching rides: offline or unavailable.');
        } else {
            console.error('Error fetching rides:', error);
        }
        throw error;
    }
};

export const getRidePoints = async (userId: string, rideId: string): Promise<RidePoint[]> => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const mapCollectionRef = collection(rideDocRef, 'map');
        const pointsDocRef = doc(mapCollectionRef, 'points');

        const pointsDoc = await getDoc(pointsDocRef);
        if (!pointsDoc.exists()) {
            return [];
        }

        const data = pointsDoc.data() as { items?: RidePoint[] };
        return data.items ?? [];
    } catch (error) {
        console.error('Error fetching ride points:', error);
        throw error;
    }
};

export const getRideAnnotations = async (userId: string, rideId: string): Promise<Annotation[]> => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');

        const annotationsDoc = await getDocs(annotationsCollectionRef);

        const annotations: Annotation[] = [];
        for (const doc of annotationsDoc.docs) {
            const data = { ...doc.data(), id: doc.id };
            annotations.push(data as Annotation);
        }

        return annotations;
    } catch (error) {
        console.error('Error fetching ride annotations:', error);
        throw error;
    }
};

export const saveRide = async (rideData: NewRideData) => {
    try {
        const userId = getAuth().currentUser?.uid;
        if (!userId) {
            throw new Error('User not authenticated');
        }
        const ridesCollectionRef = collection(firestore, 'rides');

        const batch = writeBatch(firestore);
        // Save main ride data without points
        const { points, annotations = [], generatedRoutes = [], isGPXUpload, fromWeb, ...rideDataWithoutPoints } = rideData;

        if (!points || points.length === 0) {
            throw new Error('No ride points provided');
        }

        let gpxUpload = false;
        let webSource = false;
        if (isGPXUpload) {
            gpxUpload = true;
        }
        if (fromWeb) {
            webSource = true;
        }

        const rideDocRef = doc(ridesCollectionRef);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');
        const processedAnnotations = await Promise.all(
            annotations.map(async annotation => {
                if (!annotation) {
                    return;
                }

                const annotationDocRef = doc(annotationsCollectionRef);
                const uploadMedia = async (mediaUri: string) => {
                    if (!mediaUri) {
                        return null;
                    }
                    const mediaRef = storage().ref(`rides/${rideDocRef.id}/annotations/${annotationDocRef.id}`);
                    const task = mediaRef.putFile(mediaUri);

                    task.on('state_changed', snapshot => {
                        console.log('Upload is ' + snapshot.bytesTransferred);
                    });
                    await task;
                    return await mediaRef.getDownloadURL();
                };
                batch.set(annotationDocRef, {
                    ...annotation,
                    mediaType: annotation.mediaType ?? null,
                    mediaUri: annotation.mediaUri ? await uploadMedia(annotation.mediaUri) : null,
                    id: annotationDocRef.id,
                    userId: userId,
                    rideId: rideDocRef.id,
                    createdAt: Date.now(),
                });
            })
        );

        batch.set(rideDocRef, {
            ...rideDataWithoutPoints,
            id: rideDocRef.id,
            userId: userId,
            createdAt: Date.now(),
            isGPXUpload: gpxUpload,
            fromWeb: webSource,
        });

        // Save generated routes to top-level generatedRoutes collection
        const generatedRoutesCollectionRef = collection(firestore, 'generatedRoutes');
        generatedRoutes.forEach(route => {
            const routeDocRef = doc(generatedRoutesCollectionRef, route.routeId);
            // Firestore does not support nested arrays. routePoints is LngLat[]
            // ([number, number][]), so convert each tuple to a plain object.
            const flatRoutePoints = route.routePoints.map(([lng, lat]) => ({ lng, lat }));
            batch.set(routeDocRef, {
                ...route,
                routePoints: flatRoutePoints,
                rideId: rideDocRef.id,
            });
        });

        // Save points in a single document under map/points
        const mapCollectionRef = collection(rideDocRef, 'map');
        const pointsDocRef = doc(mapCollectionRef, 'points');
        batch.set(pointsDocRef, {
            items: points,
        });

        await batch.commit();

        return rideDocRef.id;
    } catch (error) {
        // Offline / broken-DNS writes surface as the RN Firebase native-bridge quirk.
        // The caller (finishRide -> record screen) already keeps the ride data and shows
        // a "please try again" state, so log a warning instead of a red error.
        if (isTransientFirestoreError(error)) {
            console.warn('Saving ride failed (offline/unavailable) — rider can retry.');
        } else {
            console.error('Error saving ride:', error);
        }
        throw error;
    }
};

export const getRide = async (userId: string, rideId: string): Promise<FetchRideData> => {
    try {
        const ridesCollectionRef = collection(firestore, 'rides');
        const rideDocRef = doc(ridesCollectionRef, rideId);
        const rideDoc = await getDoc(rideDocRef);

        if (!rideDoc.exists()) {
            throw new Error('Trip not found');
        }
        const rideData = rideDoc.data() as FetchRideData;

        return {
            ...rideData,
            id: rideDocRef.id,
        };
    } catch (error) {
        console.error('Error getting ride:', error);
        throw error;
    }
};

export const updateRideName = async (userId: string, rideId: string, newName: string) => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        await updateDoc(rideDocRef, { rideName: newName });
    } catch (error) {
        console.error('Error updating ride name:', error);
        throw error;
    }
};

/**
 * True when a Firestore error represents a transient/offline condition rather than
 * a real bug. These are expected on flaky mobile networks and should not be logged
 * as errors or surfaced to the rider as failures.
 */
export const isTransientFirestoreError = (error: unknown): boolean => {
    if (!(error instanceof Error)) return false;
    const message = error.message.toLowerCase();
    return (
        message.includes('unavailable') ||
        message.includes('failed to get document') ||
        message.includes('network') ||
        message.includes('deadline') ||
        message.includes('offline') ||
        // When DNS/connectivity is broken, the RN Firebase native bridge can fail in
        // a way that produces a malformed error object; its own error-normalization
        // code then throws "Cannot read property 'code' of undefined" (Hermes) or
        // "Cannot read properties of undefined (reading 'code')" (V8). Treat that
        // native-bridge failure as a transient/offline condition, not a real bug.
        message.includes("property 'code' of undefined") ||
        message.includes("(reading 'code')")
    );
};

const retryWithBackoff = async <T,>(
    fn: () => Promise<T>,
    maxRetries: number = 3,
    initialDelayMs: number = 800
): Promise<T> => {
    let lastError: Error | null = null;
    for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
            return await fn();
        } catch (error) {
            lastError = error instanceof Error ? error : new Error(String(error));
            if (!isTransientFirestoreError(error) || attempt === maxRetries - 1) {
                throw error;
            }
            const delayMs = initialDelayMs * Math.pow(2, attempt);
            await new Promise(resolve => setTimeout(resolve, delayMs));
        }
    }
    throw lastError || new Error('Retry failed');
};

/**
 * Server-only aggregation queries (getCountFromServer / getAggregateFromServer)
 * cannot read from the offline cache and fail hard when the device is offline.
 * This runs a server aggregation first (with retry for transient blips) and, if
 * that fails for an offline/transient reason, falls back to reading the matching
 * documents — which DO serve from cache — and computing the value locally.
 */
const withCacheFallback = async <T,>(
    serverFn: () => Promise<T>,
    cacheFn: () => Promise<T>,
    label: string
): Promise<T> => {
    try {
        return await retryWithBackoff(serverFn);
    } catch (error) {
        if (isTransientFirestoreError(error)) {
            try {
                const cached = await cacheFn();
                console.warn(`${label}: server unavailable, served from cache.`);
                return cached;
            } catch (cacheError) {
                console.warn(`${label}: offline and no cached data available.`);
                throw cacheError;
            }
        }
        throw error;
    }
};

export const getTotalRideCount = async (userId: string): Promise<number> => {
    const ridesCollectionRef = collection(firestore, 'rides');
    const q = query(ridesCollectionRef, where('userId', '==', userId));
    return withCacheFallback(
        async () => (await getCountFromServer(q)).data().count,
        async () => (await getDocs(q)).size,
        'Total ride count'
    );
};

export const getWeeklyRideCount = async (userId: string) => {
    const ridesCollectionRef = collection(firestore, 'rides');
    const q = query(
        ridesCollectionRef,
        where('userId', '==', userId),
        where('createdAt', '>=', startOfWeek(new Date()).getTime()),
        where('createdAt', '<=', new Date().getTime())
    );
    return withCacheFallback(
        async () => (await getCountFromServer(q)).data().count,
        async () => (await getDocs(q)).size,
        'Weekly ride count'
    );
};

export const getMonthlyDistanceAndCount = async (userId: string): Promise<{ distance: number; count: number }> => {
    const ridesCollectionRef = collection(firestore, 'rides');
    const q = query(
        ridesCollectionRef,
        where('userId', '==', userId),
        where('createdAt', '>=', startOfMonth(new Date()).getTime()),
        where('createdAt', '<=', new Date().getTime())
    );
    return withCacheFallback(
        async () => {
            const snapshot = await getAggregateFromServer(q, {
                distance: sum('distance'),
                count: count(),
            });
            const data = snapshot.data() as { distance: number; count: number } | undefined;
            return { distance: data?.distance || 0, count: data?.count || 0 };
        },
        async () => {
            const snapshot = await getDocs(q);
            let distance = 0;
            for (const docSnap of snapshot.docs) {
                distance += (docSnap.data() as { distance?: number }).distance || 0;
            }
            return { distance, count: snapshot.size };
        },
        'Monthly distance'
    );
};

export const getTotalDistanceAndCountAndAverageSpeedAndElevation = async (
    userId: string
): Promise<{ distance: number; count: number; averageSpeed: number; elevation: number }> => {
    const ridesCollectionRef = collection(firestore, 'rides');
    const q = query(ridesCollectionRef, where('userId', '==', userId), orderBy('createdAt', 'desc'));
    return withCacheFallback(
        async () => {
            const snapshot = await getAggregateFromServer(q, {
                distance: sum('distance'),
                count: count(),
                averageSpeed: average('averageSpeed'),
                elevationGain: sum('elevationGain'),
            });
            const data = snapshot.data() as
                | { distance: number; count: number; averageSpeed: number; elevationGain: number }
                | undefined;
            return {
                distance: data?.distance || 0,
                count: data?.count || 0,
                averageSpeed: data?.averageSpeed || 0,
                elevation: data?.elevationGain || 0,
            };
        },
        async () => {
            const snapshot = await getDocs(q);
            let distance = 0;
            let elevation = 0;
            let speedSum = 0;
            for (const docSnap of snapshot.docs) {
                const data = docSnap.data() as { distance?: number; elevationGain?: number; averageSpeed?: number };
                distance += data.distance || 0;
                elevation += data.elevationGain || 0;
                speedSum += data.averageSpeed || 0;
            }
            const count = snapshot.size;
            return {
                distance,
                count,
                averageSpeed: count > 0 ? speedSum / count : 0,
                elevation,
            };
        },
        'Total distance'
    );
};

export const getLongestRide = async (userId: string): Promise<number> => {
    try {
        // getDocs already serves from cache when offline, so a single call is enough.
        return await retryWithBackoff(async () => {
            const ridesCollectionRef = collection(firestore, 'rides');
            const q = query(ridesCollectionRef, where('userId', '==', userId), orderBy('distance', 'desc'), limit(1));
            const snapshot = await getDocs(q);
            if (snapshot.docs.length === 0) {
                return 0;
            }
            return snapshot.docs[0].data().distance;
        });
    } catch (error) {
        if (isTransientFirestoreError(error)) {
            console.warn('Longest ride: offline, returning 0.');
            return 0;
        }
        console.error('Error fetching longest ride:', error);
        throw error;
    }
};

export const deleteRide = async (ride: FetchRideData) => {
    try {
        const rideDocRef = doc(firestore, 'rides', ride.id);
        const batch = writeBatch(firestore);
        const annotationsCollectionRef = collection(rideDocRef, 'annotations');
        const annotationsDocRefs = ride.annotations.map(annotation => {
            const mediaRef = storage().ref(`rides/${ride.id}/annotations/${annotation.id}`);
            return {
                docRef: doc(annotationsCollectionRef, annotation.id),
                mediaRef: mediaRef,
            };
        });
        annotationsDocRefs.forEach(docRef => {
            batch.delete(docRef.docRef);
            deleteObject(docRef.mediaRef);
        });
        const pointsDocRef = doc(collection(rideDocRef, 'map'), 'points');
        batch.delete(rideDocRef);
        batch.delete(pointsDocRef);
        await batch.commit();
    } catch (error) {
        console.error('Error deleting ride:', error);
        throw error;
    }
};

export const updateVisibilitySettings = async (rideId: string, visibility: boolean) => {
    try {
        const rideDocRef = doc(firestore, 'rides', rideId);
        const res = await updateDoc(rideDocRef, {
            isPublic: visibility,
        });

        console.log(res);
    } catch (error) {
        console.error('Error saving visibility settings.');
        throw error;
    }
};
