import VideoMediaView from '@/components/video/VideoMediaView';
import { getPredefinedAnnotation } from '@/lib/common/annotations';
import { AutoGeneratedAnnotation } from '@/lib/firebase-crud/annotations';
import { firestore } from '@/lib/utils/firebaseConfig';
import { fontSizes, sizes } from '@/lib/utils/responsive-sizing';
import { doc, updateDoc } from '@react-native-firebase/firestore';
import { Checkbox } from 'expo-checkbox';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import { Button, MD3Theme, Text, useTheme } from 'react-native-paper';

export default function AutoGeneratedAnnotationsScreen() {
    const theme = useTheme();
    const styles = getStyles(theme);
    const router = useRouter();
    const { autoGeneratedAnnotations, mediaUri, rideId } = useLocalSearchParams<{
        autoGeneratedAnnotations: string;
        mediaUri: string;
        rideId: string;
    }>();
    const parsedAnnotation: AutoGeneratedAnnotation[] = JSON.parse(autoGeneratedAnnotations);

    const [selectedAnnotations, setSelectedAnnotations] = useState<string[]>([]);

    useEffect(() => {
        updateDoc(doc(firestore, 'rides', rideId), {
            autoAnnotationSeen: true,
        });
    }, []);

    const toggleAnnotation = (id: string) => {
        setSelectedAnnotations(prev => {
            if (prev.includes(id)) {
                return prev.filter(annotationId => annotationId !== id);
            } else {
                return [...prev, id];
            }
        });
    };

    const handleSave = async () => {
        if (!parsedAnnotation) return;

        // Update the accepted status of auto-generated annotations
        const updatedAutoAnnotations = parsedAnnotation.map(annotation => ({
            ...annotation,
            accepted: selectedAnnotations.includes(annotation.id),
        }));

        // Update the annotation with accepted auto-generated annotations
        await updateDoc(doc(firestore, 'rides', rideId), {
            autoGeneratedAnnotations: updatedAutoAnnotations,
            autoAnnotationSeen: true,
        });

        router.back();
    };

    console.log(mediaUri);

    return (
        <View style={styles.container}>
            {mediaUri && <VideoMediaView source={mediaUri} style={styles.video} />}

            <Text style={styles.title}>{parsedAnnotation.length} annotations were generated for this video.</Text>
            <Text style={styles.subtitle}>Select annotations to keep:</Text>

            <ScrollView style={styles.annotationList}>
                <View style={styles.annotationItem}>
                    <Checkbox
                        value={parsedAnnotation.length === selectedAnnotations.length}
                        onValueChange={() => {
                            if (selectedAnnotations.length === parsedAnnotation.length) {
                                setSelectedAnnotations([]);
                            } else {
                                setSelectedAnnotations(parsedAnnotation.map(a => a.id) || []);
                            }
                        }}
                    />
                    <View style={styles.annotationContent}>
                        <Text style={styles.annotationText}>Select All</Text>
                    </View>
                </View>
                {parsedAnnotation
                    .sort((a, b) => a.startTime.localeCompare(b.startTime))
                    .map((annotation: AutoGeneratedAnnotation) => (
                        <View key={annotation.id} style={styles.annotationItem}>
                            <Checkbox
                                value={selectedAnnotations.includes(annotation.id)}
                                onValueChange={() => toggleAnnotation(annotation.id)}
                            />
                            <View style={styles.annotationContent}>
                                <Text style={styles.annotationText}>
                                    {getPredefinedAnnotation(annotation.inferredAnnotation)?.name}
                                </Text>
                                <Text style={styles.timeText}>
                                    {annotation.startTime} - {annotation.endTime}
                                </Text>
                            </View>
                        </View>
                    ))}
            </ScrollView>

            <View style={styles.buttonContainer}>
                <Button mode="contained" onPress={handleSave} style={styles.button}>
                    Save Selected Annotations
                </Button>
                <Button mode="outlined" onPress={() => router.back()} style={styles.button}>
                    Cancel
                </Button>
            </View>
        </View>
    );
}

const getStyles = (theme: MD3Theme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
            padding: sizes.medium,
        },
        title: {
            fontSize: fontSizes.small,
            fontFamily: 'LGEIHeadline-Bold',
            color: theme.colors.onSurface,
            marginBottom: sizes.medium,
        },
        subtitle: {
            fontSize: fontSizes.small,
            fontFamily: 'LGEIHeadline-Regular',
            color: theme.colors.onSurface,
            marginBottom: sizes.medium,
        },
        video: {
            width: '100%',
            height: 200,
            borderRadius: sizes.small,
            marginBottom: sizes.medium,
        },
        annotationItem: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: sizes.small,
            backgroundColor: theme.colors.surface,
            borderRadius: sizes.small,
            marginBottom: sizes.small,
        },
        annotationContent: {
            flex: 1,
            marginLeft: sizes.medium,
        },
        annotationText: {
            fontSize: fontSizes.small,
            fontFamily: 'LGEIHeadline-Regular',
            color: theme.colors.onSurface,
        },
        timeText: {
            fontSize: fontSizes.tiny,
            color: theme.colors.onSurfaceVariant,
            marginTop: sizes.tiny,
        },
        buttonContainer: {
            marginTop: sizes.large,
            gap: sizes.small,
        },
        button: {
            width: '100%',
        },
        annotationList: {
            maxHeight: 250,
        },
    });
